### ISSUE TITLE
已经bat-ria init后的项目，在git上不上传node_modules目录，怎么让bat-ria-tool重新安装

### ISSUE THREAD

**Issue by acelan86** [ecomfe/edpx-bat-ria#13]
package.json里面没有bat-ria-tool的信息，直接使用edp install 不会自动安装bat-ria-tool
这时候edp webserver启动会报错

如果用npm install bat-ria-tool不太人性化。

**Comment by Justineo** [comment]
如刚才沟通，edp 只负责前端包（`dep` 下）的引入和版本管理。后面准备在初始化时把对 npm 包的依赖写到项目的 `package.json` 里。这样如果 `.gitignore` 里忽略了 `node_modules`，clone 下来也只需要 `npm install` 一下就可以了。
