### ISSUE TITLE
运行命令与预期不符

### ISSUE THREAD

**Issue by yuyouwen** [ecomfe/edpx-bat-ria#15]
RT，运行edp bat-ria init 命令创建单页应用，目录结构有问题，和wiki中描述的不一致。node6.0和0.12.3中都是这样

**Comment by Justineo** [comment]
啥地方不对？

**Comment by yuyouwen** [comment]
都没有index.html

**Comment by Justineo** [comment]
![image](https://cloud.githubusercontent.com/assets/1726061/16189727/6a5e3f70-370e-11e6-8e0f-0f5582eb3e0f.png)

我这边好像没有你说的问题……

**Comment by yuyouwen** [comment]
我这儿上github上不了图，我hi你吧

**Comment by Justineo** [comment]
经线下沟通，是 edp-registry 路径配错的关系。
